// <auto-generated />
using System;
using CovidData.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidData.Migrations
{
    [DbContext(typeof(CovidDbContext))]
    partial class CovidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("CovidData.Model.CaseDaily", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Recovered")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("CasesDaily");
                });

            modelBuilder.Entity("CovidData.Model.CaseTotal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Recovered")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("CasesTotal");
                });
#pragma warning restore 612, 618
        }
    }
}
